### ISSUE TITLE
how to change the trigger to mouse button?

### ISSUE THREAD

**Issue by HackerKingz101** [R3nzTheCodeGOD/Valorant-External-Cheat#10]
I want change the trigger keys to RMB or MB5

**Comment by R3nzTheCodeGOD** [comment]
i tried making these keys at first but i couldn't find a library that supports those keys

**Comment by HackerKingz101** [comment]
I change _from keyboard import is_pressed_ to _from mouse import is_pressed_

its work,

but the things is, there is a bug/glitch idk what it is, its not working smoothly, can you check?

[Valorant-External-Cheat-main (HackerKingz101).zip](https://github.com/R3nzTheCodeGOD/Valorant-External-Cheat/files/6499635/Valorant-External-Cheat-main.HackerKingz101.zip)
