### ISSUE TITLE
Tried but how to edit this?

### ISSUE THREAD

**Issue by mojewjewjews** [R3nzTheCodeGOD/Valorant-External-Cheat#14]
Its perfectly working now, can you help me modify the code? Changing the shift key to auto? no need to push the shift button? or change na shift key bind to rmb?

**Comment by mojewjewjews** [comment]
Its done I binded the right click from mouse module. Seems working while using snipe.

**Comment by mojewjewjews** [comment]
now that it is working is it okay if you teach me how to move the cursor in the middle if it detects the color?

**Comment by R3nzTheCodeGOD** [comment]
You can move the mouse using the "pyautogui" library
