### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by M96L-9** [R3nzTheCodeGOD/Valorant-External-Cheat#15]
![image](https://user-images.githubusercontent.com/76674579/119184557-e8718780-ba4b-11eb-99bd-95a272633c0c.png)
 
 how to fix this ?

**Comment by NameLord** [comment]
Do you have the game on fullscreen or fullscreen windowed ?

**Comment by R3nzTheCodeGOD** [comment]
## #15
Are you using dual monitors ?
Try a different version of "mss" library

**Comment by M96L-9** [comment]
yes i have 2 monitors, and i play in full screen
