### ISSUE TITLE
holdkey does not work

### ISSUE THREAD

**Issue by iramsesvl** [R3nzTheCodeGOD/Valorant-External-Cheat#27]
triggerbot doesn't work when I press shift, toggle key mode works perfectly, but I'm interested in the holdkey function

**Comment by R3nzTheCodeGOD** [comment]
## Tested, no problem found

1. "IsHoldKey" must be set to true in the resulting config file.
2. Selected key names must be written correctly in the config file

![image](https://user-images.githubusercontent.com/58574988/122534534-4c777380-d02b-11eb-9b8a-89adee9ce064.png)
![image](https://user-images.githubusercontent.com/58574988/122534771-86487a00-d02b-11eb-9268-ef3ae1597b59.png)
