### ISSUE TITLE
Immense Keyboard Input Delay

### ISSUE THREAD

**Issue by justicecs** [R3nzTheCodeGOD/Valorant-External-Cheat#6]
When using either the exe or the code, both give keyboard input delay in and out of valorant. I'm not sure why, but the game is nearly unplayable at some points because of this. Is there a reason for this?

**Comment by R3nzTheCodeGOD** [comment]
**It definitely originated from the "keyboard" library. I will review this library and come back.**

**Comment by R3nzTheCodeGOD** [comment]
# İssue #6
**I looked for "keyboard" library problems and no one reported a problem, I suspect my own code, but no problem, no delay when using the code.**

**Note: You can edit the source code for this project to work more efficiently. The code works extremely well for me.**

OS: Windows `10`
Python version: `3.8.9`
Keyboard lib version: `0.13.5`
