### ISSUE TITLE
How to optimize to another color?

### ISSUE THREAD

**Issue by SAYNEY** [R3nzTheCodeGOD/Valorant-External-Cheat#8]
I dont understand logic of your color check function. I wanna optimize this for rgb(210,67,34). Can you explain me?please:)

**Comment by R3nzTheCodeGOD** [comment]
### I can give you an example like this

```py
enemy_red: int = 210
enemy_green: int = 67
enemy_blue: int = 34
tolerance: int = 15


def color_check(red: int, green: int, blue: int) -> bool:
    return (enemy_red - tolerance < red < enemy_red + tolerance) and (enemy_green - tolerance < green < enemy_green + tolerance) and (enemy_blue - tolerance < blue < enemy_blue + tolerance)
```

**Comment by SAYNEY** [comment]
Ok, it work and now i understand this logic.
But second question is: Is this code work only with window-mode?
First versions is working with full-window mode.

**Comment by R3nzTheCodeGOD** [comment]
You must use the full screen windowed mode to capture images from the game, but if it works,
use full screen.

**Comment by saucyv777** [comment]
I'm a complete noob I have an arduino Leonardo and have no clue what I am doing. Can you break it down more for me please. Thank you!
